#!/bin/bash
#SBATCH --job-name=HomotopyOpt
#SBATCH --time=01-23:10
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --chdir=/work/himmelmann1/CRNHexagon/src/   # working directory of the job
#SBATCH -o ./run.out
#SBATCH --mail-type=ALL              # always get mail notifications

export http_proxy=http://proxy2.uni-potsdam.de:3128
export https_proxy=http://proxy2.uni-potsdam.de:3128

# Specify the path to the config file
julia -e "include(\"testEDRetraction.jl\")"