indent = 4
margin = 110
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = false
import_to_using = false
pipe_to_function_call = true
short_to_long_function_def = true
always_use_return = false